supabase/storage

src/routes/object/getObject.ts
src/routes/object/getPublicObject.ts
src/routes/object/getSignedObject.ts
src/types/types.d.ts
src/utils/s3.ts

fixes https://github.com/supabase/storage-api/issues/20
Video and Audio files should play better now

feat: add support for byte range requests

---

src/routes/object/getObject.ts
src/routes/object/getPublicObject.ts
src/routes/object/getSignedObject.ts
src/utils/index.ts

changes content type of html files to `text/plain`

feat: disable rendering html files

---

Dockerfile

we dont deploy on fly for testing anymore since we can test locally

fix: docker startup command

---

.github/workflows/build.yml

compilation of native module xattr was failing cos python wasn't found

fix: arm build, install python for native node module builds

---

.github/workflows/docs.yml

fixes https://github.com/supabase/storage-api/issues/49

fix: docs github action

---

.github/workflows/build.yml
gh-Dockerfile

xattr.node had to be packaged manually cos pkg couldn't do it. 
Revisit after updating pkg if this is still required

fix build: pkg was unable to package xattr

---

.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/docs.yml
Dockerfile
package-lock.json
package.json

feat: update to node 14

---

src/backend/s3.ts
src/routes/object/getObject.ts
src/routes/object/getPublicObject.ts
src/routes/object/getSignedObject.ts
src/types/types.d.ts

`accept-ranges` and `content-length` are required headers for cdns to stream media content properly

fix streaming with cdn

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/release.yml
Dockerfile
package-lock.json
package.json

Feature.
Node.js v14 was being used.
Node.js v16 will be used.

feat: bump Node.js version to v16

---

src/test/object.test.ts
src/utils/index.ts

Bug fix
Objects with no name can be created.
Objects with no name cannot be created.

fix: prevent creation of objects with no name

---

src/admin-app.ts
src/app.ts
src/monitoring/logger.ts
src/plugins/log-request.ts
src/plugins/log-tenant-id.ts
src/plugins/postgrest.ts
src/routes/bucket/createBucket.ts
src/routes/object/updateObject.ts
src/server.ts
src/utils/config.ts

Improvement
- Not all the useful request infos are logged (ex, tenant ID)
- health check requests are logged
- postgrest URL scheme was hard coded to http
- We now log the tenant id on each request as well as non-sensitive headers
- We now exclude the `/status` endpoints from the requests logs it will reduce the amount of logs produced
- postgrest URL scheme is not an environment variable and can be switched to use HTTPS

chore(logging): improve logging

---

src/backend/s3.ts
src/renderer/imgproxy.ts
src/routes/render/renderAuthenticatedImage.ts
src/routes/render/renderPublicImage.ts

Fix & Improvements
- fix: S3 signed URL needs to be encoded before passing it to imgproxy
- reduce signed URL time to 5mins
- add X-Transformation header with transformation options

Image resizing improvements

---

src/routes/render/renderAuthenticatedImage.ts
src/routes/render/renderPublicImage.ts

Fix
typo on joining transformation params
join values delimited by coma

fix: transform header

---

src/utils/config.ts
src/utils/index.ts

fix
branch has linting  issues

Fixing linting

---

.github/workflows/mirror.yml
.github/workflows/release.yml

ci
publish images to ghcr for faster CLI start time on GHA

chore: add ghcr image mirror

---

src/config.ts
src/queue/events/webhook.ts
src/storage/uploader.ts

Increasing webhook queue pull interval

fix: increase webhook queue interval

---

src/queue/queue.ts

application name reflects that it is pgboss and more aggressive archival of completed jobs - changed to 4 hours from 12 hours

fix: modify pgboss settings

---

src/config.ts
src/storage/backend/index.ts
src/storage/backend/s3.ts

fixes https://github.com/supabase/storage-api/issues/252
enhancement
does not work with localstack or minio
now works with localstack and minio

set forcePathStyle when using S3 endpoint

---

src/http/schemas/transformations.ts
src/storage/renderer/image.ts
src/test/db/docker-compose.yml

Feature
Passthrough the "Accept" header to imgproxy for automatic webp detection

feat: support automatic webp detection for image transformation

---

src/http/routes/object/getSignedURL.ts
src/storage/object.ts

Bug fix
- Add format to signed url token
- Do not include metadata if empty

fix: format on signed url

---

src/http/routes/render/index.ts
src/http/schemas/transformations.ts
src/storage/renderer/image.ts

feature
Add `quality` parameter to image transformation

feat: add quality option, image transformation

---

src/http/schemas/transformations.ts
src/storage/renderer/image.ts

Bug fix
use an opt-in approach for AVIF format

fix: opt-in support for avif

---

.github/workflows/docs.yml

* https://github.com/actions/runner-images/issues/6002

chore: update GH Actions runner to use Ubuntu 22.04

---

src/storage/backend/file.ts

Fixes #274, more details in the issue description.
I looked at how to implement a unit test. My understanding is that only the S3Backend implementation is tested.

fix: move files between distinct directories (#274)

---

src/http/routes/render/renderPublicImage.ts

fix: respect RLS image transformation

---

migrations/multitenant/0005-add-db-pool-options.sql
src/http/routes/tenant/index.ts

Feature
Adds pooling configuration options to multitenant db

feat: add mulitenant pooling options

---

migrations/tenant/0015-add-version.sql
package-lock.json
package.json
src/config.ts
src/http/routes/object/getObject.ts
src/http/routes/object/getObjectInfo.ts
src/http/routes/object/getPublicObject.ts
src/http/routes/object/getSignedObject.ts
src/http/routes/render/renderAuthenticatedImage.ts
src/http/routes/render/renderPublicImage.ts
src/http/routes/render/renderSignedImage.ts
src/storage/backend/file.ts
src/storage/backend/generic.ts
src/storage/backend/s3.ts
src/storage/database.ts
src/storage/object.ts
src/storage/renderer/asset.ts
src/storage/renderer/head.ts
src/storage/renderer/image.ts
src/storage/renderer/renderer.ts
src/storage/schemas/object.ts
src/storage/uploader.ts
src/test/bucket.test.ts
src/test/object.test.ts
src/test/x-forwarded-host.test.ts

Feat
In preparation for a major refactor to the data layer of storage-api, this PR will make the future code backwards compatible

feat: backwards compatible object versioning

---

package.json

previous run failed - https://github.com/supabase/storage-api/actions/runs/4649068615

feat: trigger release

---

.env.sample
.prettierignore
src/auth/jwt.ts
src/database/client.ts
src/database/connection.ts
src/database/tenant.ts
src/http/plugins/db.ts
src/http/plugins/storage.ts
src/http/routes/bucket/index.ts
src/http/routes/object/index.ts
src/http/routes/render/index.ts
src/http/routes/tus/index.ts
src/queue/events/base-event.ts
src/storage/database/adapter.ts
src/storage/database/knex.ts
src/test/db/docker-compose.yml
src/test/object.test.ts
src/test/tus.test.ts
src/test/webhooks.test.ts
src/test/x-forwarded-host.test.ts

Bug fix
Refactor connection pooler to be more efficient

fix: refactor multi-tenant connection pooler

---

src/storage/database/knex.ts

When the pg user doesn't have permission to switch to a role, the transaction was never rolled back
Bug fix
Rollback the transaction

fix: release connection when can't switch to role

---

.github/workflows/release.yml
package-lock.json

fix: semantic release version

---

.github/workflows/release.yml

Relates to https://github.com/cycjimmy/semantic-release-action/issues/159

fix: downgrade to node 14 for semantic version, see linked issue

---

src/database/connection.ts
src/http/routes/object/moveObject.ts
src/http/routes/tus/lifecycle.ts
src/queue/events/base-event.ts
src/storage/object.ts
src/storage/uploader.ts
src/test/rls.test.ts
src/test/rls_tests.yaml

Bug fix
Passing the owner column on previously missing test permission checks will make sure that if you wrote RLS
against the owner column, they will pass

fix: pass owner to test permission

---

src/http/routes/tus/handlers.ts

Bug fix
Move block to try / catch to handle exception gracefully

fix: move block on try/catch

---

src/http/routes/tus/handlers.ts

Bug fix
Pass owner to upload check

fix: add owner check

---

src/storage/object.ts

Bug fix
Uses the old file version
Uses the new file version

fix: copy command using the new version

---

package-lock.json
package.json

Deps updates 
Update AWS dependencies
Updated AWS SDK libraries

fix: aws dependency updates

---

.github/workflows/release.yml
src/app.ts
src/config.ts
src/http/plugins/tenant-id.ts
src/http/routes/tenant/index.ts

Feature
- Implement Tenant health check route
- Implement route that returns the current storage version

feat: tenant health-check + storage version

---

.github/workflows/ci.yml

Bug fix
External PR's will be able to run properly

fix: trigger action on pull_request_target

---

.github/workflows/ci.yml

CI: change pr target

---

src/database/migrations/migrate.ts

Bug fix,
Start single migration strategy when progressive mode is on

fix: start single migration strategy

---

src/storage/object.ts
src/test/rls.test.ts

Bug fix
Currently move checks RLS on old data
Rls on move will provide the new object and will require SELECT and UPDATE on the object table
Fixes #399

fix: rls check on move

---

src/http/plugins/signature-v4.ts

Related to #449 
pass the config as an option

fix: pass config on Signature

---

src/http/plugins/log-request.ts

Bug fix
use req.executionError instead of reply

fix: error log edge case

---

.github/workflows/mirror.yml
.github/workflows/release.yml
Dockerfile

Bug fix
- Upgrade alpine base image
- add the latest tag to all registries

fix: docker base image upgrade

---

.github/workflows/mirror.yml
.github/workflows/release.yml

CI fix
Do not try to push :latest on ecr, use mirrors to push latest

fix: ecr mirrors

---

.github/workflows/release.yml

Bug fix
Please link any relevant issues here.
Use correct version for mirroring images

fix: ci mirror image step

---

src/http/routes/tus/lifecycle.ts
src/storage/protocols/s3/signature-v4.ts

Bug fix
Fixed proxy headers for protocols

fix: proxy headers for protocols

---

package-lock.json
package.json

Deps updates
Updates:
- Aws Libs
- Axios
Fixes securities alerts

fix: deps update

---

src/storage/renderer/info.ts

Bug fix
Return x transformation options

fix: return x-transformation options if provided

---

src/http/routes/object/getObject.ts
src/http/routes/object/getObjectInfo.ts
src/http/routes/tus/lifecycle.ts
src/storage/protocols/s3/signature-v4.ts

Bug fix
- Fixes #543 
- Revert to 404 when no authentication token is provided

fix: check for existance of port on host

---

src/internal/monitoring/otel.ts
src/storage/protocols/tus/postgres-locker.ts

Bug fix
- Release locker when LockerResource is thrown

fix: tus locker release

---

src/internal/concurrency/index.ts
src/internal/monitoring/otel.ts
src/internal/streams/byte-counter.ts
src/internal/streams/index.ts
src/internal/streams/monitor.ts
src/internal/streams/stream-speed.ts
src/storage/backend/s3.ts

Feature
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.

fix: stream monitoring

---

src/internal/streams/monitor.ts
src/internal/streams/stream-speed.ts

Improvement
Adds much more useful information to stream monitoring instead of simply bps.
```json
[
{
"stream.speed": 5832704,
"stream.bytesRead": 5832704,
"stream.status": {
"paused": false,
"closed": false
}
},
{
"stream.speed": 5242880,
"stream.bytesRead": 11075584,
"stream.status": {
"paused": false,
"closed": false
}
},
{
"stream.speed": 5242880,
"stream.bytesRead": 16318464,
"stream.status": {
"paused": false,
"closed": false
}
},
...
]
```

fix: adds more info on stream monitoring

---

src/http/routes/s3/commands/complete-multipart-upload.ts

Bug fix
Change Parts with Part in the API contract for CompleteMultipartUpload

fix: s3 parts typo

---

migrations/multitenant/0014-disable-tenants-events.sql
src/http/routes/admin/tenants.ts
src/internal/database/tenant.ts
src/internal/queue/event.ts
src/storage/events/webhook.ts
src/test/tenant.test.ts

Feature
- Allow specific events to be disabled for specific tenants.
- The Webhook event is a single event, however, to disable specific webhook events (and not all) we can use `Webhook:EventName`

feat: allow disabling specific events

---

src/internal/monitoring/otel.ts

Bug fix
Use startIncomingHook to add custom Otel metadata

fix: otel hook

---

.github/workflows/docs.yml
.github/workflows/release.yml

Bug fix
Upgrade ubuntu version to 24 for CI

fix: ci ubuntu version

---

package-lock.json
package.json
src/storage/backend/file.ts

Bug fix
bump xattr version compatible with ubuntu 24

fix: xattr version

---

.github/workflows/release.yml

Bug fix
upgrade node for ci release action

fix: ci version on ci release

---

.github/workflows/release.yml

Bug fix
upgrade semantic release plugin

fix: upgrade semantic release pluging

---

.github/workflows/release.yml

fix: semantic version plugin for ci

---

package-lock.json
package.json
src/storage/backend/file.ts

Revert fx-attrs version upgrade

fix: revert fxattrs-upgrade

---

src/config.ts
src/http/plugins/db.ts
src/http/routes/admin/migrations.ts
src/http/routes/admin/tenants.ts
src/internal/database/connection.ts
src/internal/database/migrations/migrate.ts
src/internal/database/migrations/progressive.ts
src/scripts/migrate-call.ts
src/start/server.ts
src/storage/events/run-migrations.ts

Feature
Allows to freeze storage to a certain migration even if new migrations are added

feat: freeze migration name

---

src/storage/scanner/scanner.ts

Bug fix
use the correct field name for paginating keys

fix: pagination scanner

---

src/http/routes/object/getSignedObject.ts
src/http/routes/object/updateObject.ts

Removed a couple logs that are no longer needed and an unused import

chore: remove duplicate logging, remove unused import

---

package-lock.json
package.json

chore(deps): bump axios from 1.7.4 to 1.9.0

---

src/http/plugins/signature-v4.ts
src/http/routes/s3/commands/put-object.ts
src/http/routes/s3/commands/upload-part.ts
src/storage/protocols/s3/s3-handler.ts
src/storage/protocols/s3/signature-v4-stream.ts
src/storage/protocols/s3/signature-v4.ts
src/storage/uploader.ts
src/test/signature-v4-stream.test.ts

Bug fix / Feature
Not supporting chunked uploads, producing a corrupted file
Support S3 chunked upload:
- https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html
- https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html
Fixes #577

fix: support s3 chunked upload

---

src/storage/object.ts
src/test/s3-protocol.test.ts

Bug fix
Pagination fails when listing directories using S3 protocol with url encoding enabled because the continuation token contents was being url encoded.
Don't url encode the continuation token contents.
By default aws cli and rclone enable url encoding so this fixes pagination on both. This only impacts listing nested objects (objects with a `/` delimiter in their name)
Fixes #686

fix: support S3 pagination with path prefix and url encoding enabled

---

src/internal/database/pool.ts
src/internal/monitoring/metrics.ts
src/internal/monitoring/otel.ts
src/start/server.ts

Improvement
- Disable tracing completely when is turned off
- add pool metric to know how many internal pools are created

fix: improve monitoring

---

src/internal/database/pool.ts
src/test/pool.database.test.ts

Bug fix
Will reset the pool so that it can be re-created

fix: pool cleanup

---

src/storage/backend/s3/adapter.ts

Bug fix
When uploading zero byte objects (aka adding a placeholder to create a folder). We make a head call to S3 to get object info  which often takes a long time to complete. For some reason this only happens on zero byte objects.
Don't make a head call for zero byte objects and instead use static values.

fix: do not make head calls for zero byte uploads to S3 backend

---

src/http/routes/render/renderAuthenticatedImage.ts

Bug fix
- Incorrect operation for auth rendered image
- Correctly using the right operation for auth render image

fix: correct operation for auth render image

---

jest.config.cjs
package-lock.json
package.json
src/internal/cluster/cluster.ts
src/internal/cluster/eks.ts

* Introduces cluster discovery for running storage in a kubernetes setup (EKS). This mode requires 2 new env vars to be set:
* `KUBERNETES_NAMESPACE`: the namespace for which storage is running in
* `KUBERNETES_LABEL_SELECTOR`: the label selector for the pods to be discovered

feat: add cluster discovery for eks

---

src/scripts/migrate-call.ts

Bug fix
CLI relies on migration failures to be reported with non-zero exit code.

fix: ensure failure exit code is properly reported
