supabase/storage

- src/routes/bucket/createBucket.ts
- src/routes/bucket/deleteBucket.ts
- src/routes/bucket/emptyBucket.ts
- src/routes/bucket/getAllBuckets.ts
- src/routes/bucket/getBucket.ts
- src/routes/object/copyObject.ts
- src/routes/object/createObject.ts
- src/routes/object/deleteObject.ts
- src/routes/object/deleteObjects.ts
- src/routes/object/getObject.ts
- src/routes/object/getSignedObject.ts
- src/routes/object/getSignedURL.ts
- src/routes/object/listObjects.ts
- src/routes/object/moveObject.ts
- src/routes/object/updateObject.ts
- src/test/bucket.test.ts
- src/test/generic-routes.test.ts
- src/test/object.test.ts
- src/utils/generic-routes.ts
- refactor: create two generic methods and use them to avoid repetition
**Note:** There is still a lot of repetition, especially on routes, but this pull-request can help remove duplication
Both behaviours remain the same.
> The open-source community is incredible!
**Note:** Sorry for the extensive pull-request...
> refactor: create two generic methods and use them to avoid repetition

- src/app.ts
The api for fastify-multipart changed somewhere in between and this option needs to be passed in to change to the old behaviour
> Fix: file size limit check

- src/routes/bucket/index.ts
- src/routes/object/createObject.ts
- src/routes/object/index.ts
- src/routes/object/updateObject.ts
Pipe the request stream for these content types instead of the default handling. See https://www.fastify.io/docs/latest/ContentTypeParser/.
`text/plain` and `application/json` MIME type are uploaded in Storage Buckets as empty files.
`text/plain` and `application/json` MIME type are uploaded in Storage Buckets correctly.
> fix: #43 use custom content type parser for application/json and text/plain

- .github/workflows/build.yml
- gh-Dockerfile
recent version of pkg seems to handle bundling xattr.node in the binary well
> fix: xattr no longer required in release builds

- src/backend/s3.ts
- src/routes/object/getObject.ts
- src/routes/object/getPublicObject.ts
when client aborted a request to storage server, it kept the socket open for 300 seconds. S3 SDK couldn't open any more sockets after there were 50 open idle sockets (which is the default). 
This PR reduces the socket idle timeout from 300 seconds to 3 seconds and explicitly shows the maxsockets parameter so that it can be finetuned later
fixes https://github.com/supabase/infrastructure/issues/1064
> Fix: 499 errors

- src/backend/file.ts
- src/backend/generic.ts
- src/backend/s3.ts
- src/routes/object/getObject.ts
- src/routes/object/getPublicObject.ts
- src/routes/object/getSignedObject.ts
- src/test/bucket.test.ts
- src/test/object.test.ts
> Forward 304 and If-Modified-Since/If-None-Match headers

- src/routes/tenant/index.ts
Database may not be ready yet on tenant insertion. Instead, migrations would be deferred until first getting the tenant config.
> Do not run migrations on tenant insertion

- src/utils/migrate.ts
Migration was throwing "connect ETIMEDOUT" errors only after ~2 mins.
> Add 1s connection timeout for migration database client

- src/test/db/02-storage-schema.sql
Signed-off-by: Bariq <bariqhibat@gmail.com>
Bug fix, feature, docs update, ...
Bug fix #12
We assume that the name of the file is `cat.jpg`, getting the extension is by getting the second index of the split by '.'.
However, files can have multiple '.', hence this PR introduces a more general implementation.
Please link any relevant issues here.
Reverse the string, split it by '.' and get the first item, reverse the string again. We'll get the last index of the split '.'.
Feel free to include screenshots if it includes visual changes.
> fix extension function by getting the last item of a split

- src/utils/migrate.ts
Needs to be run as a superuser.
> Revert "fix: do not track SQL statements when running migrations"

- migrations/tenant/0007-add-public-to-buckets.sql
so that the server can continue startup in case the migration was already run
> make migration idempotent

- migrations/tenant/0007-add-public-to-buckets.sql
This reverts commit 47b12abd40a6355f79d47bf17b8ce00e9b2a2d14, which is causing error "Migration failed. Reason: Hashes don't match for migrations '0007-add-public-to-buckets.sql'. This means that the scripts have changed since it was applied."
> fix: revert "make migration idempotent"

- src/routes/object/getSignedURLs.ts
- src/routes/object/index.ts
- tsconfig.json
@inian I'm using `prefixes` for consistency with the other batch API: https://github.com/supabase/storage-api/blob/fd072d448f3d860ad5f404406c7f09c025826206/src/routes/object/deleteObjects.ts#L31. However, we aren't using those strings as prefixes there, and aren't doing so here either. Do you recall why they're named `prefixes`, should we rename to say, `paths`, and be inconsistent with the delete objects endpoint?
> feat: add endpoint to get signed URLs

- src/server.ts
Running migrations for all tenants is taking too long on startup. We cache tenant configurations and run migrations on demand if the tenant configuration isn’t already cached, doing that on startup is just a performance optimisation, which can be delayed.
> fix: only cache tenant configurations and run migrations after servers start listening

- .github/workflows/release.yml
- .gitignore
- package.json
Fixes:
```
pkg/prelude/bootstrap.js:1740
throw error;
^
Error: Cannot find module '/snapshot/storage-api/node_modules/pg-format/lib/reserved.js'
Require stack:
- /snapshot/storage-api/node_modules/pg-format/lib/index.js
- /snapshot/storage-api/node_modules/pg-listen/dist/index.js
- /snapshot/storage-api/node_modules/pg-listen/index.js
- /snapshot/storage-api/dist/utils/tenant.js
- /snapshot/storage-api/dist/plugins/postgrest.js
- /snapshot/storage-api/dist/routes/bucket/index.js
- /snapshot/storage-api/dist/app.js
- /snapshot/storage-api/dist/server.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from …
```
> fix: include `pg-format/lib/reserved.js` in `pkg` `assets`

- Dockerfile
- ecosystem.config.js
As a temporary mitigation for nodejs/node#39671.
> feat: use PM2 in `Dockerfile`

- src/app.ts
In a recent incident, the `maxEventLoopUtilization` check led to 503's being returned for all requests even though the requests were being processed, albeit intermittently, in spurts of every half to one second. We should instead continue to process requests and rely on Auto Scaling. Without any checks, `under-pressure` is simply exposing a `/status` route, but it ain't broke.
> fix: remove `under-pressure` `maxEventLoopUtilization` check

- src/routes/bucket/emptyBucket.ts
The current batch size can cause 414 URI too long errors when the PostgREST URL for deletion is more than 16K in length. 16K is the default for Kong/NGINX. Each object adds UUID length (36) + "%2C" (3) to the URL. 39*300=12K, well below 16K.
> fix: reduce object deletion batch size when emptying bucket from 500 to 300

- package-lock.json
- package.json
- src/admin-app.ts
- src/app.ts
`maxEventLoopUtilization: 0.99` should have been removed for the admin app. under-pressure had been retained since it was already exposing a working status route, but might as well remove it if that's all it does.
> fix: remove under-pressure

- src/routes/bucket/emptyBucket.ts
- src/routes/object/deleteObjects.ts
- src/routes/object/getSignedURLs.ts
- src/test/db/03-dummy-data.sql.sample
- src/test/object.test.ts
- src/utils/config.ts
Current URL lengths are unbounded so they can cause 414 URI too long errors when the PostgREST URL is more than ~8K characters, when PostgREST is behind Kong/NGINX, since ~8K is the default limit for Kong/NGINX: http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers.
> fix: limit URL length when getting signed URLs, deleting objects and emptying bucket

- src/admin-app.ts
The per-route metrics support for fastifyv3 also collects metrics for
any route encountered by the service, which provides a mechanism for
DoS'ing secondary systems. Disabling these metrics until we upgrade to
v4, where discarding non-registered routes is supported.
> chore: temporarily disable route metrics

- src/backend/file.ts
- src/backend/s3.ts
- src/routes/object/createObject.ts
- src/test/object.test.ts
- src/utils/errors.ts
Bug fix
If an error occurs while uploading a new file, the associated row in `storage.objects` still exists even though the file might not exist on the storage backend (#125).
Any errors thrown when uploading a new file will be caught, and associated rows from `storage.objects` table will be removed.
> fix: ensure that newly inserted rows are deleted when uploading fails

- .github/workflows/ci.yml
- Dockerfile
- package-lock.json
- package.json
Dependencies update.
Currently Node.js v16 is being used.
- Node.js v18 will be used in the Docker image.
- `pkg` dependency is also removed since it is no longer used in the build process.
Node.js v18.6.0 looks like it addresses https://github.com/supabase/storage-api/issues/141.
> fix: upgrade to Node.js v18

- src/app.ts
Feature
Swagger (OpenAPI v2) is used for the documentation.
OpenAPI v3 is used.
> feat: switch to OpenAPI v3

- Dockerfile
- docker-entrypoint.sh
This PR is to add an entry point file `docker-entrypoint.sh` to Docker image, which will enable use of Docker file-based secrets as mentioned in https://github.com/supabase/supabase/issues/6014.
Currently this Docker image only supports environment variable based secrets, file-based secrets `*_FILE` are not supported but is suggested by Docker in https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images.
File-based Docker secrets `*_FILE` will be supported and fall back to environment variable secrets.
N/A
> feat: support docker file-based secrets

- src/routes/object/getObject.ts
- src/routes/object/getPublicObject.ts
- src/routes/object/getSignedObject.ts
- src/test/object.test.ts
feature
we can only rely on HTML tags to download a file
Adds a new query string parameter `filename` which if provided the file will be forced to be downloaded by the browser
by adding the content-disposition header
Closes https://github.com/supabase/storage-api/issues/122
> feat: force downloading file when providing filename

- src/monitoring/logger.ts
- src/plugins/log-request.ts
fix
Currently we log the entire request url
We want to exclude the `token` query string parameter from the logs
> fix: exclude token query string from logs

- src/routes/object/getObject.ts
- src/routes/object/getPublicObject.ts
- src/routes/object/getSignedObject.ts
- src/test/bucket.test.ts
- src/test/object.test.ts
bug fix
Browser (or other client) never cache the images from storage: https://github.com/supabase/storage-api/issues/193
When setting the `last-modified` header, use `toUTCString` to ensure the date format adheres to [the rfc2616 spec](https://datatracker.ietf.org/doc/html/rfc2616#section-3.3.1)
- I learned that all of these response headers are not yet tested (eg all tests are passing even after I removed all of these lines). This PR mocks the request headers and asserts the response headers
https://github.com/supabase/storage-api/blob/6e2ae7a521db22af37f8d612cdfab6ad00ca4c9f/src/routes/object/getObject.ts#L81-L85
- For running the tests multiple times, it seemed that we can't run them without restarting the whole container. Running jest twice failed for me because I think there is no …
> fix: use correct format for last modified date header

- src/routes/object/getObject.ts
Add a `HEAD` Method to `getObject` route so clients can get headers without requesting whole object.
I get a `400` which is ok but a 405 would be better 😂 
A `HEAD` request just like the `GET` but without the body (see https://github.com/fastify/fastify/pull/2700/)
> add HEAD Mehthod to getObjects route

- .env.sample
- .github/workflows/ci.yml
- package-lock.json
- package.json
- src/app.ts
- src/backend/file.ts
- src/backend/generic.ts
- src/backend/s3.ts
- src/renderer/imgproxy.ts
- src/routes/render/index.ts
- src/routes/render/renderAuthenticatedImage.ts
- src/routes/render/renderPublicImage.ts
- src/test/bucket.test.ts
- src/test/db/04-dummy-data.sql.sample
- src/test/db/docker-compose.yml
- src/test/render-routes.test.ts
- src/utils/config.ts
Feature
Currently is not possible to do image transformations on the fly
With this PR `storage-api` will be able to offload image processing to imgproxy and return the transformed image.
2 New endpoints have been introduced:
- `/storage/v1/render/public/<bucket>/<key>`
- `/storage/v1/render/authenticated/<bucket>/<key>`
Currently supported processing options:
- `width`
- `height`
- `resize`
> feat: image resizing with imgproxy backend

- src/utils/config.ts
- src/utils/index.ts
- To make supabase storage support multiple JWT verify algorithm (e.g. RS256)
- To support base64 of`PGRST_JWT_SECRET`
The verifyJWT function does not support RS256 here https://github.com/supabase/storage-api/blob/9bf39cd2b5f897b55b60a4af7cadc8b5f53b33af/src/utils/index.ts#L37
The verifyJWT function support RS256 and other algorithms.
> fix(jwt): support multi-algorithm of JWT verify

- src/routes/object/getSignedObject.ts
- src/routes/object/getSignedURL.ts
- src/routes/object/getSignedURLs.ts
- src/test/object.test.ts
- src/types/types.d.ts
Feature.
Users are unable to customize the response HTTP headers when creating signed URLs.
When creating signed URLs, users can customize the response content type and content disposition HTTP headers. 
Both S3 and Google Cloud Storage have this feature:
- S3: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/classes/getobjectcommand.html
- allows customizing the following headers as well: content-language, expires, cache-control, content-encoding
- GCS:
- https://cloud.google.com/storage/docs/xml-api/reference-headers#responsecontentdisposition
- https://cloud.google.com/storage/docs/xml-api/reference-headers#responsecontenttype
- only allows customizing the response content type and disposition
I've gone with allowing only the response content type and …
> feat(signed URLs): allow customizing response headers

- .releaserc
Bug fix
Sometimes CI doesn't pickup conventional commits properly
The default preset is `angular` now is changed to `conventionalcommits`
> fix: commit analyzer preset

- src/http/error-handler.ts
- src/http/routes/object/getPublicObject.ts
Bug fix
Currently, we bubble up S3 error to the client when accessing a non-existing public object 
We will return 404
> fix: Handle 404 gracefully for public objects

- .env.sample
- src/config.ts
- src/http/error-handler.ts
- src/queue/events/base-event.ts
- src/queue/queue.ts
- src/server.ts
- src/storage/errors.ts
- src/test/object.test.ts
- src/test/webhooks.test.ts
- src/test/x-forwarded-host.test.ts
Bug Fix
- The current version enforces pg-boss migration at start-up
#224 
- pg-boss disabled by default to keep it backward compatible. You can enable it with (`ENABLE_QUEUE_EVENTS`)
- optional `PG_QUEUE_CONNECTION_URL` to install and operate pg boss
> fix: optional queue + error code

- .env.sample
- .github/workflows/ci.yml
- src/app.ts
- src/config.ts
- src/http/routes/render/index.ts
- src/http/routes/render/renderAuthenticatedImage.ts
- src/http/routes/render/renderSignedImage.ts
- src/storage/backend/s3.ts
- src/storage/renderer/image.ts
- src/test/render-routes.test.ts
Fixes
- render route is too generic
- is not possible to transform images using a signed URL
- downloading transformed image is not supported
- renamed render route to be more explicit `/render/image` 
- support signed URL transformations
- support download for transformed images
- Improved error handling
- renamed ENV variable `DISABLE_IMAGE_TRANSFORMATION` to `ENABLE_IMAGE_TRANSFORMATION`
> fix: renaming render routes + enchantments

- src/queue/queue.ts
- src/storage/object.ts
Bug fix
If we try to move an object to a destination that is the same as the source we end up deleting the file
Prevent move operations to the same destination as the source
> fix: prevent move operation to the same destination

- src/auth/jwt.ts
- src/http/error-handler.ts
- src/http/routes/object/getSignedURL.ts
- src/http/routes/render/renderAuthenticatedImage.ts
- src/http/routes/render/renderPublicImage.ts
- src/http/routes/render/renderSignedImage.ts
- src/http/schemas/transformations.ts
- src/storage/object.ts
- src/storage/renderer/image.ts
- src/test/render-routes.test.ts
Bug fix
transforming signed URL assets is currently done when requesting the resource
the transformation parameters are now part of the JWT token and can't be changed once the token is signed
> fix: embed transformation params in the signed url token

- src/http/routes/object/getSignedURL.ts
- src/http/routes/render/renderAuthenticatedImage.ts
- src/http/routes/render/renderPublicImage.ts
- src/http/schemas/transformations.ts
- src/test/render-routes.test.ts
Bug fix
Query string params are used in a POST request to determine transformations
Use body to pass transformations params
> fix: use body instead of query params

- src/http/schemas/transformations.ts
- src/storage/renderer/image.ts
fix
mapping imgproxy resize_type with custom values
- Rename `fit` to `contain`
- Rename `fill` to `cover`
- Rename `force` to `fill`
> fix: map resizing options

- src/auth/jwt.ts
- src/http/routes/object/getSignedObject.ts
- src/http/routes/render/renderSignedImage.ts
- src/storage/object.ts
- src/storage/renderer/image.ts
- src/storage/renderer/renderer.ts
- src/test/webhooks.test.ts
Bug fix
- etags were out of sync with S3 during copy and move operations
- signed URL is using `cache-control` header instead of `expires` which means that the CDN cache doesn't honor the JWT expiry date
- etags are now in sync with s3 during copy and move operations
- signed URL now returns the `expires` header with the date set as the JWT expiry date
> fix: consistent etags + use expires header on signed urls

- src/monitoring/logger.ts
chore
Whitelist x-client-trace-id to be logged
> chore: whitelist x-client-trace-id header to be logged

- src/storage/backend/file.ts
This PR is to fix `The file system does not support extended attributes or has the feature disabled` error on macOS.
See:
https://github.com/supabase/supabase/issues/10745
https://github.com/supabase/supabase/discussions/9539
When trying to upload a file/image using to a locally hosted supabase instance, get the error:
`The file system does not support extended attributes or has the feature disabled`
There should be no error.
After this fix, user also need to enable `VirtioFS` in Docker desktop to be able to set file attribute.
> fix: unsupported extended file attributes on macOS

- src/http/schemas/transformations.ts
- src/storage/renderer/image.ts
- src/test/db/docker-compose.yml
Bug fix
Webp support needed to be opt-in by using a query string param
Automatic webp detection without additional parameters, use `format: origin` to disable this behaviour
> automatic webp support by default

- src/http/routes/tenant/index.ts
Bug fix
Do not default feature image transformation to false when updating the tenant
> fix: do not default image transformation flag

- Dockerfile
- ecosystem.config.js
- migrations/tenant/0013-use-bytes-for-max-size.sql
- package-lock.json
- package.json
- src/app.ts
- src/config.ts
- src/http/routes/bucket/createBucket.ts
- src/http/routes/bucket/getBucket.ts
- src/http/routes/bucket/updateBucket.ts
- src/monitoring/logger.ts
- src/storage/backend/s3.ts
- src/storage/database.ts
- src/storage/limits.ts
- src/storage/object.ts
- src/storage/renderer/image.ts
- src/storage/schemas/bucket.ts
- src/storage/storage.ts
- src/storage/uploader.ts
- src/test/bucket.test.ts
- src/test/db/04-dummy-data.sql.sample
- src/test/object.test.ts
Feature
- Allow creating buckets specifying a `file size limit` and white-listing `mime-types` which will serve for validating the file during upload
- Allow to update these values via the bucket update endpoint 
- Validate max file size and mime type during upload
> feat: allow to customise max file size and mime types at bucket level

- src/config.ts
- src/http/routes/render/rate-limiter.ts
Bug fix
no timeout
Add redis connection timeout and command timeout
> fix: redis connection timeout on rate limiter

- src/http/routes/bucket/createBucket.ts
- src/http/routes/bucket/updateBucket.ts
- src/http/routes/object/getSignedURL.ts
- src/storage/renderer/image.ts
Bug fix
- Resize type is now respected on signed rendered urls
- Integer first in validation param validation
> fix: resize type on signed url

- migrations/tenant/0014-add-can-insert-object-function.sql
- src/auth/jwt.ts
- src/config.ts
- src/http/routes/object/getSignedUploadURL.ts
- src/http/routes/object/index.ts
- src/http/routes/object/uploadSignedObject.ts
- src/storage/database.ts
- src/storage/object.ts
- src/test/object.test.ts
Introduces a new feature to sign an upload url, which allows for uploading straight to the bucket without credentials.
It's currently not possible to upload a file from the client side, without routing it through your own server, which is not the preferred way.
You can now presign a upload url with your service token, and give the url to any client which can then upload the file directly.
Closes https://github.com/supabase/storage-api/issues/81
This PR fixes things from https://github.com/supabase/storage-api/pull/244. Thanks to @MagnusHJensen for prior work!
> feat(object): Allow for presigning upload url

- Dockerfile
fixes https://github.com/supabase/cli/issues/932
relates to https://github.com/supabase/cli/issues/268
pm2 is no longer used to start node process so it's safe to remove
fixes error when pulling storage images in [docker rootless mode](https://docs.docker.com/engine/security/rootless/), ie.
```bash
docker image pull supabase/storage-api:v0.34.0
```
pm2 depends on nssocket which owns files with an arbitrarily large uid/gid. That breaks on docker rootless mode: https://github.com/moby/moby/issues/43576
```bash
gitpod /workspace/cli (main) $ docker image pull supabase/storage-api:v0.34.0
v0.34.0: Pulling from supabase/storage-api
f56be85fc22e: Pull complete 
51fa4270e0cc: Pull complete 
a89e758f145e: Pull complete 
d3f921cbf16e: Pull complete 
45ce1000756e: Extracting …
```
> fix: remove unused pm2 from global installation

- src/database/connection.ts
- src/storage/uploader.ts
- src/test/db/docker-compose.yml
Bug fix
Limit knex connection pool to 1 when using an external pool
> fix: limit connection pool to 1 when using external pool

- src/database/client.ts
- src/http/plugins/db.ts
Bug fix
Correctly pass down headers to postgres setting
> fix: connection headers

- src/http/routes/object/createObject.ts
- src/http/routes/object/updateObject.ts
- src/storage/database/adapter.ts
- src/storage/database/knex.ts
- src/storage/object.ts
- src/test/object.test.ts
Patch
No ID is returned
Return object is one file upload
relates #284
> patch: return file id on upload

- migrations/tenant/0017-add_owner_id_column_deprecate_owner.sql
- src/monitoring/logger.ts
- src/storage/database/knex.ts
- src/storage/limits.ts
- src/storage/object.ts
- src/storage/schemas/object.ts
- src/test/tus.test.ts
feature
- Deprecate `owner` column in favor of `owner_id` 
- owner_id is now of type `text`
- Write to both columns if the owner is uuid, otherwise only on the `owner_id` column
> feat: deprecate owner column in favour of owner_id

- package-lock.json
- package.json
- src/config.ts
- src/database/connection.ts
- src/storage/database/knex.ts
- src/test/object.test.ts
- src/test/rls.test.ts
- src/test/webhooks.test.ts
- tsconfig.json
Improvement
- Remove manual polling when not using external pool, rely on reapInterval
- Add search path within the transaction
- Remove `propagateCreateError` config it as knex recommends to keep it set to `true`
- Lowered default connection timeout to 3s
- Fix S3 dependencies resolutions from previous dep-bot
> pool settings improvements

- package-lock.json
- package.json
- src/database/connection.ts
Bug fix
If the underline database pool is full (ex pgBouncer) and trying to acquire a new transaction the request will fail with:
```
no more connections allowed (max_client_conn)
```
Adding retry login when acquiring the transaction and the max connection is thrown. We will retry acquiring the transaction and not fail the request
> Retry acquiring transaction when pool reaches max_num_connection

- src/http/routes/object/getSignedURLs.ts
Bug fix,
the path was not returned in the signURLs endpoint
The path is now returned
closes https://github.com/supabase/storage-api/issues/353
> fix: return path in the sign-urls endpoint

- src/config.ts
- src/database/connection.ts
- src/database/migrate.ts
- src/queue/queue.ts
feature
By setting the env variable `DATABASE_SSL_ROOT_CERT` storage api will connect via SSL with `sslmode=verify-ca`
> fix: support enforcing SSL connection

- src/http/routes/tenant/index.ts
Bug fix
Database pool URL cannot be set to empty
allow setting the databasePoolUrl to empty string
> fix: allow updating the poolUrl to empty string

- src/database/connection.ts
- src/http/error-handler.ts
- src/storage/errors.ts
Bug fix
When trying to acquire a connection on a overloaded database results in a 500 error
This PR handle this error gracefully returning the following status codes:
- 544 
- when a timeout occur while trying to acquire a connection
- 429 
- When too many requests are sent concurrently and pgBouncer is unable to accept any more clients, resulting in max_client connection
- When no more Postgres connections are allowed for these users
> fix: handle database overload gracefully

- src/config.ts
- src/queue/events/object-admin-delete.ts
- src/queue/events/webhook.ts
Performance improvement
Queue jobs are fetched and processed one at the time
We increase the number of jobs fetched in a single call to reduce overall queries issued to the database as well as decrease the load.
We also run 5 concurrent jobs at any point instead of 1
> fix: increase queue concurrency

- Dockerfile
Bug fix
VERSION env is not passed into the container via build args
assign VERSION env from build-args VERSION
> fix: add version env to dockerfile

- src/database/connection.ts
- src/http/error-handler.ts
Bug fix
Currently the error handler for detecting too many connections is located at the connection level, however this issue can happen in more than one place
The error is now handled at the main error handler level
> fix: move database overload error handler

- src/http/routes/tenant/index.ts
Bug fix
Currently there is no way to remove the databasePoolUrl if set
Allowing removing the databasePoolUrl if sending null
> fix: allow setting null poolUrl

- src/http/routes/bucket/createBucket.ts
Bug fix
When explicitly passing null to the id field during bucket creation the id is not set
id defaults to the bucket name when not defined
> fix: default bucketId during creation

- src/database/connection.ts
- src/storage/database/knex.ts
Bug fix
Listeners seems to be still registered even when the connection is closed
Remove all unnecessary listeners
> performance / fix remove listeners on query and connection

- src/config.ts
- src/database/connection.ts
- src/http/plugins/metrics.ts
- src/http/plugins/storage.ts
- src/http/routes/tus/s3-store.ts
- src/monitoring/metrics.ts
- src/queue/events/base-event.ts
- src/queue/queue.ts
- src/storage/backend/index.ts
- src/storage/backend/s3.ts
- src/storage/database/knex.ts
- src/storage/uploader.ts
- src/test/rls.test.ts
- src/test/tus.test.ts
Bug fix
- Everytime a queue message calls `createStorage` each storage client uses a different HTTP pool agent not taking advantage of keep-alive
- All metrics requires the `tenant_id` label, which creates high cardinality metrics
- All events are now sharing a single HTTP agent pool 
- reduce metrics cardinality by removing the `tenant_id` label
> use a singleton http agent for queue events + Reduce metrics cardinality

- src/storage/uploader.ts
- src/test/object.test.ts
Improve error message clarity
When uploading an object to supabase storage, the mime type is checked against the allowed mime types on the bucket. If the mime type is not allowed, an error message is reported, but the message does not say what the mime type was.
Before:
```
mime type not supported
```
If the mime type is not allowed, the message informs the user what mime type was attempted:
```
mime type ${mimeType} is not supported
```
I got stuck on a really hairy problem today that took quite a bit of digging to figure out. Here's what happened:
* I used `fetch()` to retrieve a photo from a URL. This resulted in a `Blob` type.
```ts
const blob: Blob = await fetch(url).then(res => res.blob())
```
* I used `upload()` to put that image into object storage. (Note: I already had the …
> Improve invalid_mime_type error to report the attempted mime type

- src/config.ts
- src/storage/uploader.ts
Feature
Currently the max file size value is shared between TUS uploads and Standard upload
This PR introduces an optional `FILE_SIZE_LIMIT_STANDARD_UPLOAD` to limit the file size only for Standard uploads
> feat: optional file size limit on standard upload

- .github/workflows/cli.yaml
CI
When a release is published, an automatic PR is sent to the Supabase CLI repo with the new version update
> chore(ci): automaticaly update cli repo on tag release

- .github/workflows/ci.yml
> ci: bump node to 20

- src/storage/storage.ts
- src/storage/uploader.ts
Bug fix
When explicitly passing `contentType: text/vtt;charset=utf-8` the charset is not retained in the response
honor the content type provided in the form data
Fixes #366
> fix: content-type charset

- .env.sample
- docker-compose-infra.yml
- docker-compose.yml
- src/auth/jwt.ts
- src/config.ts
- src/database/tenant.ts
- src/http/plugins/jwt.ts
- src/http/routes/object/getSignedObject.ts
- src/http/routes/object/uploadSignedObject.ts
- src/http/routes/render/renderSignedImage.ts
- src/http/routes/tus/index.ts
- src/storage/object.ts
- src/test/bucket.test.ts
- src/test/object.test.ts
Feature
Currently, the `TENANT_ID`, `SERVICE_KEY`, `REGION` and `ANON_KEY` env variables are required to run storage in single-tenant mode
- the `SERVICE_KEY`  env is now optional. 
When not provided, the service will generate one at boot time using the `AUTH_JWT_SECRET` 
- `SERVER_REGION` is now optional, and only used in metrics. (default `not-specified`)
`STORAGE_S3_REGION` is used as the aws region (default `REGION`)
- the `TENANT_ID` env is now optional defaulting to `storage-single-tenant`
- `ANON_KEY` is now deprecated as the service is not currently using it
This PR will simplify even further self-hosting for storage
Example Docker Compose to launch storage in single tenant:
```yaml
version: '3'
services:
storage:
image: supabase/storage-api:latest
ports:
- '5000:5000'
- …
```
> feat: default service-key for single tenant

- migrations/tenant/0002-storage-schema.sql
- migrations/tenant/0019-alter-default-value-objects-id.sql
Feature
Currently, the storage schema relies on the `ossd-uuid` extension specifically on the `uuid_generate_v4()` function.
Storage drops support for PG 12 - and is now only compatible with > PG 13, which allows us to use the built-in function `gen_random_uuid` and remove dependencies on other extensions.
pgcrypto extension was also removed since there was no usage in the code-base
> Remove postgres extensions dependencies

- src/config.ts
- src/storage/renderer/head.ts
- src/storage/renderer/renderer.ts
feature
This PR implements a couple of interesting features
- allow the CDN to cache assets for longer useing the `s-maxage` directive configurable with `S_MAXAGE` env (default 0)
- use `stale-while-revalidate` when the origin detects that the requested etag header doesn't match with what we have in the metadata, resulting in the CDN serving stale content for 30s after the initial fetch. This will increase performance.
- the HEAD rendered will now instruct the CDN that `must-revalidate` when a request is sent to origin with a different etag
Unlocks Smart-CDN-V2
> Feat: stale-while-revalidate

- src/http/error-handler.ts
Bug fix
Handle max clients connection error, supavisor
> fix: handle max clients connection error, supavisor

- .github/workflows/ci.yml
- src/config.ts
Bug fix
DB_INSTALL_ROLES default to true
DB_INSTALL_ROLES default to false
> fix: db install roles default env to false

- src/database/migrate.ts
- src/database/tenant.ts
- src/http/routes/tus/lifecycle.ts
- src/monitoring/logger.ts
Add pg client on error handler
> fix: add error handler on client

- src/storage/backend/file.ts
Added Content-Range capability to the File adapter allowing for video streaming.
Storage module would not honour range requests when requesting video files from buckets files by clients using the public URL. Video players request video files with range values to improve loading performance. The File adapter would ignore these ranges and return the entire file, causing an excessive delay when attempting to play a large video file (ie: 1gb). 
File adapter checks for the existence of the Range header, then returns the appropriate chunk of the requested file. If the header is not present then it returns to the standard response containing the entire file.
> Add Content-Range capability to the File getObject adapter.

- src/http/routes/object/getObjectInfo.ts
Bug fix
Always check if the bucket is public on info requests
> fix: check for public bucket on info request

- src/config.ts
- src/database/migrations/migrate.ts
- src/queue/events/base-event.ts
- src/storage/protocols/s3/signature-v4.ts
feature
Not possible to run the S3 protocol on CLI, the x-forwarded-header is always overwritten from kong
- Allow using the arbitrary `Forwarded` header to determine the host
- Increase database migrations timeout to 60s
- disable host check on queue events
> Accept forwarded header on S3 signature

- src/http/routes/s3/index.ts
Bug fix
Some S3 Clients tries to parse headers if returned as empty causing issues.
Empty headers are not returned
> fix: exclude empty headers on S3 protocol

- package-lock.json
- package.json
- src/http/plugins/xml.ts
- src/http/routes/s3/commands/upload-part.ts
- src/http/routes/s3/index.ts
- src/http/routes/s3/router.ts
- src/storage/backend/file.ts
- src/storage/object.ts
Bug fix
- removed @types/ajv since they are shipped with the lib
- disable bodyParser for PutObject requests (improves performance)
- fix xattr metadata for s3 multi-part upload
- fix equality check for copying objects across buckets
> Fix s3 file driver xattr

- src/http/routes/s3/commands/get-object.ts
- src/http/routes/s3/commands/upload-part.ts
- src/storage/backend/adapter.ts
- src/storage/backend/file.ts
- src/storage/backend/s3.ts
- src/storage/protocols/s3/s3-handler.ts
- src/storage/protocols/s3/signature-v4.ts
- src/storage/renderer/image.ts
- src/test/s3-protocol.test.ts
Bug fix
- Add object tagging stub endpoint so that aws cli works as intended when copying across buckets
- Whitelist additional headers
- remove cache-control from non-signable headers (aws SDK actually signs it)
- Implemented PartCopy command on file driver
> fix: add object tagging stub endpoint

- docker-compose.yml
- src/http/plugins/xml.ts
- src/monitoring/logger.ts
- src/storage/object.ts
- src/storage/protocols/s3/s3-handler.ts
Bug fix
- S3 Upload Multipart requires RLS policies on the `s3_multipart_uploads` and `s3_multipart_uploads_parts` tables
- Move object command required SELECT + UPDATE + INSERT
- Removed the need for RLS policies in `s3_multipart_uploads` and `s3_multipart_uploads_parts`
- Only policies to the `objects` table are required to derive the access control for the MultiPart upload
- Move object command only requires SELECT source + INSERT destination RLS policy
> Consistent RLS access for S3 session token

- src/database/connection.ts
- src/http/error-handler.ts
Bug fix
When there is an error during the creation of a transaction, there is a bug in knex https://github.com/knex/knex/issues/4709 where the error is not consistent and propagated.
This PR patches this weird behaviour by awaiting the `exectionPromise` if the transaction is already marked as completed. Forcing the exception to bubble up.
> fix: knexjs edge case on transaction

- src/auth/jwt.ts
- src/http/routes/object/getSignedUploadURL.ts
- src/http/routes/object/uploadSignedObject.ts
- src/storage/object.ts
- src/test/object.test.ts
feature
Currently is not possible to use signed upload URL to overwrite files
Allows providing x-upsert header for signed upload URL and overwrite files
Closes #380
> feat: allow upload signed url to overwrite files

- src/app.ts
- src/auth/jwt.ts
- src/database/connection.ts
- src/http/plugins/jwt.ts
- src/http/routes/index.ts
- src/http/routes/object/getSignedUploadURL.ts
- src/http/routes/object/uploadSignedObject.ts
- src/http/routes/tus/index.ts
- src/http/routes/tus/lifecycle.ts
- src/storage/errors.ts
- src/storage/object.ts
- src/test/object.test.ts
- src/test/tus.test.ts
Feature
Signed upload URL were not supported for the TUS protocol
Supporting signed upload URL for the TUS protocol, allowing non-authenticated users to upload via TUS by having this time-limited URL
Example client implementation:
```ts
const { data, error } = await supabase
.storage
.from('avatars')
.createSignedUploadUrl('folder/cat.jpg')
const upload = new tus.Upload(file, {
endpoint: `${localServerAddress}/upload/resumable/sign`,
headers: {
'x-signature': data.token,
},
metadata: {
bucketName: 'avatars',
objectName: 'folder/cat.jpg',
contentType: 'image/jpeg',
cacheControl: '3600',
},
onError: function (error) {
console.log('Failed because: ' + error)
},
onSuccess: () => {
console.log('success')
},
})
upload.start()
```
Implementation details:
Tus URL for signed uploads: …
> feat: Signed Upload URL for TUS

- src/http/routes/tus/lifecycle.ts
Bug fix
validate the signed URL by specifically checking on `/upload/resumable/sign` the previous version was using the `tusPath` which doesn't work when there is a URL rewrite.
> fix: tus signed upload url validation

- src/storage/protocols/s3/s3-handler.ts
Bug fix
Do not return the `NextContinuationToken` if empty. Some clients such as mountpoint-s3 doeasn't handle this field gracefully when empty
> fix: omit nextcontinuation token when empty

- src/config.ts
- src/http/plugins/log-request.ts
- src/http/plugins/signature-v4.ts
- src/monitoring/logger.ts
- src/storage/errors.ts
- src/storage/protocols/s3/signature-v4.ts
- src/test/s3-protocol.test.ts
Feature
S3 Signed URLs were not supported
S3 Signed URLs are now supported
Closes https://github.com/supabase/storage/issues/465
> feat: s3 Signed URLs

- src/storage/protocols/s3/signature-v4.ts
- src/test/s3-protocol.test.ts
Bug fix
- Refactored SignatureV4 class to make it more readable
- When signing keys with the AWS CLI for fetching an object, the payloadHash is UNSIGNED.
This PR will honour this behaviour
> fix:  S3 GET presigned urls

- src/config.ts
- src/queue/queue.ts
- src/worker.ts
Feature
This PR allows turning on/off queue workers in the container.
Beneficial if you want to run 2 sets of containers, one only with the API and the other with queue workers
> feat: allow to disable queue workers

- src/database/migrations/migrate.ts
- src/database/migrations/progressive.ts
- src/http/routes/admin/tenants.ts
Bug fix
When a tenant is being created, we first try to run the migrations and then register the target.
This sometimes causes the tenant to never be added if the database is not currently reachable
Migrations are now run after the tenant creation.
If an error occur during the migrations, we schedule a job to re-run async with a queue job
> fix: run migrations after tenant creation

- src/storage/limits.ts
- src/storage/uploader.ts
- src/test/object.test.ts
Bug fix
When the mime-type is set, creating empty folders fails
Empty folders can still be created
Closes #503 this PR also restricts `emptyFolders` to 0kb
> Allow creating folders even if the mime type validation is set

- src/internal/concurrency/async-abort-controller.ts
- src/internal/concurrency/index.ts
- src/internal/database/migrations/migrate.ts
- src/internal/database/migrations/progressive.ts
- src/internal/errors/codes.ts
- src/internal/monitoring/otel.ts
- src/internal/pubsub/adapter.ts
- src/internal/pubsub/postgres.ts
- src/internal/queue/queue.ts
- src/server.ts
- src/shutdown.ts
- src/test/rls.test.ts
- src/worker.ts
Chore
If one of the components crashes before the server is fully started, we are not gracefully shutting down other services.
- Shared shutdown procedure for worker and api
- Use AbortSignals to notify shutdown
- Always clean up successful started services
> More robust shutdown process

- src/internal/queue/queue.ts
Bug fix
only includes params if provided
> fix: queue optional delete params

- src/storage/object.ts
Just adds defense-in-depth that Storage can't be used as a signing oracle (an all-knowing entity you can tell to "sign" things for you) that would allow bypassing PostgREST RLS.
It achieves this by disallowing any `role` metadata to ever be supplied to the `signObjectUrl` method.
> feat: prevent passing in `role` claim in presigned URL JWTs

- src/storage/protocols/s3/signature-v4.ts
Bug fix
Certain clients expect the content-lenght set to 0 when no body is provided.
This PR set the content-lenght to 0 when not provided
> fix: s3 signature on strict clients

- src/storage/object.ts
Bug fix
When the copy command fails because an asset already exists or you don't have permission, we won't send a queue event.
> fix: when copy fails do not emit event

- migrations/tenant/0025-custom-metadata.sql
- src/http/plugins/db.ts
- src/internal/database/migrations/migrate.ts
Improvement
This PR introduces a new `---SYNC---` token in the migrations files which will force the migrations to run before the request  is handled.
Once the migrations have run, the service will continue to use progressive migrations.
> fix: allow sync migrations

- src/config.ts
- src/http/routes/tus/index.ts
- src/storage/object.ts
- src/storage/protocols/s3/s3-handler.ts
- src/storage/protocols/tus/postgres-locker.ts
Feature
When copying onto a destination that already exists was not possible, this PR allows for future protocol compatibilities to accept upserts on copy
> feat: allow overwriting objects when copying

- src/http/plugins/jwt.ts
- src/http/routes/object/getObject.ts
- src/http/routes/object/getObjectInfo.ts
- src/storage/database/knex.ts
- src/storage/storage.ts
- src/test/object.test.ts
Feature
Currently, we use `/public` and `/authenticated` endpoints to determine the access control
This PR modifies the route without the `/public` or `/authenticated` endpoint, which allows authentication to happen at the route level.
This fixes many issues on downloading objects or fetching info without knowing their privacy control
> feat: handle authentication on top level routes

- src/storage/object.ts
Bug fix
When copying across buckets, there was a bug in the edge case where you are:
- copying across buckets
- the destination key already exists
- the destination key is the same name as the source
When all of the 3 scenario happens,
It would cause the file to be copied just fine, but it would delete the original.
This PR fixes this unwanted behaviour, and will correctly not delete the original file
> fix: use destinationBucket on copy

- package-lock.json
- package.json
- src/http/plugins/storage.ts
- src/http/plugins/tracing.ts
- src/http/routes/object/deleteObject.ts
- src/http/routes/object/updateObject.ts
- src/http/routes/object/uploadSignedObject.ts
- src/http/routes/s3/commands/upload-part.ts
- src/http/routes/tus/index.ts
- src/internal/monitoring/metrics.ts
- src/internal/monitoring/otel-instrumentation.ts
- src/internal/monitoring/otel.ts
- src/storage/backend/adapter.ts
- src/storage/backend/s3.ts
- src/storage/events/base-event.ts
- src/storage/object.ts
- src/storage/protocols/s3/s3-handler.ts
- src/storage/uploader.ts
- src/test/object.test.ts
Monitoring 
- Adding Prometheus metrics to agentkeepalive pool 
- Adding abort signals to upload
- More spans on aws Uploader class 
- Updated fastify from 4.8.0 to 4.28.0
- Updated to typescript 5
> fix: add metrics for agentkeepalive

- .eslintrc.js
- package-lock.json
- package.json
- src/config.ts
- src/http/plugins/signals.ts
- src/http/plugins/tenant-id.ts
- src/http/plugins/tracing.ts
- src/http/routes/tus/index.ts
- src/storage/backend/index.ts
- src/storage/backend/s3.ts
- src/test/jwt.test.ts
- src/test/s3-protocol.test.ts
Chore
- Revert: single S3 client (no performance gain)
- try / catch on tracing middleware
- added appVersion to the logs
- default s3Timeout 0 (no timeout)
> fix: use a single client

- src/http/plugins/log-request.ts
- src/http/plugins/signals.ts
- src/http/plugins/tracing.ts
- src/http/routes/object/createObject.ts
- src/http/routes/s3/index.ts
- src/internal/auth/jwt.ts
- src/internal/database/tenant.ts
- src/internal/monitoring/logger.ts
- src/internal/monitoring/otel.ts
- src/internal/pubsub/postgres.ts
- src/start/server.ts
- src/storage/backend/s3.ts
- src/storage/object.ts
- src/storage/protocols/s3/s3-handler.ts
Monitoring
- Add tracing to more methods on the `aws/s3-client`
- pass abort signal to the createObject method
- convert std library imports to node ejs style
- add delay to close connection when aborting
> fix: add more tracing on Uploader

- .github/workflows/docs.yml
- src/http/error-handler.ts
- src/http/plugins/log-request.ts
- src/http/plugins/signals.ts
- src/http/plugins/tracing.ts
- src/internal/concurrency/index.ts
- src/internal/concurrency/stream.ts
- src/internal/errors/codes.ts
- src/storage/backend/s3.ts
- src/storage/protocols/s3/s3-handler.ts
- src/storage/protocols/s3/signature-v4.ts
Bug fix
- This PR fixes the edge case where aborted request prints logs twice
- Add a passthrough stream which watches the data flowing
- on Abort we add to the trace bytes uploaded and bytes read
> Watch upload stream + fix duplicate logs

- src/scripts/export-docs.ts
Fixed docs export command to exit gracefully
> fix: docs-export

- src/http/plugins/storage.ts
- src/http/routes/tus/index.ts
- src/internal/concurrency/stream.ts
- src/internal/http/agent.ts
- src/internal/http/index.ts
- src/internal/queue/event.ts
- src/internal/queue/queue.ts
- src/scripts/export-docs.ts
- src/storage/backend/adapter.ts
- src/storage/backend/file.ts
- src/storage/backend/s3.ts
- src/storage/events/base-event.ts
Monitoring
- Monitor the upload stream every 1s and add useful information to traces
> fix: upload stream monitoring

- src/config.ts
- src/http/plugins/tracing.ts
- src/internal/monitoring/otel.ts
- src/storage/backend/s3.ts
- src/storage/renderer/info.ts
Improvement
- Only enable telemetry in logs when `TRACING_MODE=debug|logs` - we should turn this off when not needed.
- Allow to toggle on / off telemetry for upload
> fix: optional debug telemetry

- .github/workflows/docs.yml
- src/http/plugins/db.ts
- src/internal/queue/queue.ts
- src/storage/events/base-event.ts
- src/storage/object.ts
Bug fix
- Fixed an issue where the migrate-call was initialising the Storage Adapter causing the script to fail
- Fixed Docs push
- do not await promises on errors hooks
> fix: base event storage initialisation

- migrations/multitenant/0012-image-transformation-limits.sql
- src/http/routes/admin/tenants.ts
- src/http/routes/render/renderAuthenticatedImage.ts
- src/http/routes/render/renderPublicImage.ts
- src/http/routes/render/renderSignedImage.ts
- src/internal/database/tenant.ts
- src/storage/renderer/image.ts
- src/test/tenant.test.ts
Feature
Allow customising the max_resolution limit that imgproxy will impose for specific tenants.
Default is `NULL` (default)
this env `IMGPROXY_ALLOW_SECURITY_OPTIONS` is necessary in imgproxy for this to work
> feat: allow increasing resolution on a per tenant basis

- src/storage/backend/adapter.ts
- src/storage/backend/file.ts
- src/storage/backend/s3.ts
- src/storage/object.ts
- src/storage/protocols/s3/s3-handler.ts
- src/test/s3-protocol.test.ts
Bug fix
Metadata can now be overwritten when using the CopyObject command
Fixes #580
> fix: S3 Protocol allow overwriting metadata on copy

- src/storage/protocols/s3/s3-handler.ts
Bug fix
Fixes a typo in the response for the DeleteObjects command of the S3 protocol
> fix: s3 delete reponse typo

- src/config.ts
- src/http/plugins/signature-v4.ts
- src/http/routes/tus/lifecycle.ts
- src/internal/monitoring/logger.ts
- src/storage/protocols/s3/signature-v4.ts
Feature
Allow supporting `x-forwarded-path` to determine paths dynamically for generated URL
Opt-in feature with the env var: `REQUEST_ALLOW_X_FORWARDED_PATH`
> feat: support x-forwarded-path

- src/http/plugins/db.ts
- src/internal/database/client.ts
- src/internal/database/connection.ts
Bug fix
At times the `storage.operation` flag is not passed as a config when using the S3 protocol
This PR fixes this inconsistency by using a function to compute the value when necessary
> fix: operation on s3 protocol

- migrations/multitenant/0013-s3-protocol-toggle.sql
- src/config.ts
- src/http/routes/admin/tenants.ts
- src/http/routes/s3/index.ts
- src/internal/database/tenant.ts
- src/test/tenant.test.ts
- src/test/x-forwarded-host.test.ts
Feature
Allow disabling the S3 protocol on a per-tenant basis as well as when running Storage in single tenant mode using `S3_PROTOCOL_ENABLED=false`
> feat: allow disabling s3 protocol

- src/internal/monitoring/logflare.ts
Monitoring
Log an error to Stderr when storage is unable to push logs to logflare
> fix: log when unable to send logs to logflare

- package-lock.json
Deps update
Cross-spawn regex vulnerability: https://github.com/supabase/storage/security/dependabot/51
old version: 7.0.3 -> fixed vulnerability 7.0.6
Severity: Low
code paths doesn't allow inputs from `glob` and the rest of the dependencies are dev-dependencies as listed below
```
storage-api % npm ls cross-spawn                      
supa-storage@1.11.2 /Users/fenos/Documents/Code/storage-api
├─┬ eslint@8.57.1
│ └── cross-spawn@7.0.6
├─┬ glob@11.0.0
│ └─┬ foreground-child@3.3.0
│   └── cross-spawn@7.0.6 deduped
└─┬ jest@29.2.2
└─┬ @jest/core@29.2.2
└─┬ jest-changed-files@29.2.0
└─┬ execa@5.1.1
└── cross-spawn@7.0.6 deduped
```
> fix: upgrade cross-spawn

- package-lock.json
- package.json
- src/http/plugins/signature-v4.ts
- src/http/plugins/xml.ts
- src/http/routes/object/createObject.ts
- src/http/routes/object/updateObject.ts
- src/http/routes/object/uploadSignedObject.ts
- src/http/routes/s3/commands/put-object.ts
- src/http/routes/s3/commands/upload-part.ts
- src/http/routes/s3/index.ts
- src/http/routes/s3/router.ts
- src/http/routes/tus/lifecycle.ts
- src/storage/object.ts
- src/storage/protocols/s3/s3-handler.ts
- src/storage/protocols/s3/signature-v4.ts
- src/storage/uploader.ts
- src/test/s3-protocol.test.ts
Feature
- Support for [POST Upload](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html) for the S3 Protocol 
-  Major refactor to the `Uploader` class so that it is not coupled to the `FastifyRequest` allowing for much more granular control on how to upload files depending on the method we receive the stream 
TODO: Upload conditions
[EDIT]
Upload conditions will be implemented in a future PR.
The only condition that is now support is `Expiry`
> feat: s3 post handler

- src/storage/object.ts
Bug fix
When using special characters such as the `+` S3 treats it as a space
By encoding the key on copy S3 correctly identify the object key correctly
> fix: storage encoding on copy

- src/http/plugins/jwt.ts
- src/http/plugins/log-request.ts
This PR removes deprecated properties from fastify. Currently we are getting this waring while running the server and tests
(node:55925) [FSTDEP016] DeprecationWarning: You are accessing the deprecated "request.routeConfig" property. Use "request.routeOptions.config" instead. Property "req.routeConfig" will be removed in fastify@5.
Deprecated warnings are shown while running the server
Deprecated warnings are removed while running the server
> fix: remove fastify deprecated properties

- package.json
- src/http/plugins/db.ts
- src/http/routes/admin/migrations.ts
- src/http/routes/admin/tenants.ts
- src/internal/database/index.ts
- src/internal/database/migrations/migrate.ts
- src/internal/database/migrations/progressive.ts
- src/internal/database/tenant.ts
- src/scripts/migrate-call.ts
- src/start/server.ts
- src/storage/database/adapter.ts
- src/storage/database/knex.ts
- src/storage/events/run-migrations.ts
- src/storage/events/webhook.ts
Bug fix
Restructuring imports to prevent import cycles. 
package: `@internal/database/migrations` is now a stand-alone package.
- Moved tenant migrations logic outside of the tenants.ts file
> fix: cleanup imports

- src/http/plugins/signature-v4.ts
- src/http/routes/s3/commands/put-object.ts
- src/test/s3-protocol.test.ts
Bug fix
Modifying the default (10MB) of fastify multipart to 5GB as the maximum limit accepted.
Downstream we have the right file size validation
> fix: default 5GB limit as max-file size

- .env.sample
- src/config.ts
- src/storage/backend/file.ts
Fix #612 
#612
In the file backend, ETags are generated by calculating the MD5 hash of the entire file contents, which can take several seconds or even more than 10 seconds for larger files. This becomes particularly problematic when utilizing Range requests.
The ETag in the file backend is now generated using only a file's modification time (`mtime`) and `size`. I believe this is sufficient as it follows the same [approach used by Nginx](https://github.com/nginx/nginx/blob/57d54fd922e7ecbebb78598d13adc9df1a4b69c0/src/http/ngx_http_core_module.c#L1701C23-L1706) (and moreover, the file backend is primarily used in local development).
> feat: Add `mtime` as optional ETag algorithm in file backend alongside default `md5`

- src/http/routes/object/getObjectInfo.ts
This is a bug fix in which in Object info did not return bucket_id, last_accessed_at, last_modified which is present in interface FileObjectV2 {
id: string
version: string
name: string
bucket_id: string
updated_at: string
created_at: string
last_accessed_at: string
size?: number
cache_control?: string
content_type?: string
etag?: string
last_modified?: string
metadata?: Record<string, any>
}
In the current behavior bucket_id, last_accessed_at, last_modified were not returned.
https://github.com/supabase/storage/issues/591
https://github.com/supabase/storage/issues/541
In the new behavior these will be returned
> fix: added bucket_id and updated_at on object info

- src/http/routes/object/copyObject.ts
- src/http/routes/s3/commands/copy-object.ts
- src/storage/backend/s3/adapter.ts
- src/storage/object.ts
- src/storage/protocols/s3/s3-handler.ts
- src/storage/uploader.ts
- src/test/object.test.ts
- src/test/s3-protocol.test.ts
Bug fix / Feature
Copying objects to the same destination is not supported
- Allow copying objects to same destination
- Allow overwriting cacheControl & mimetype
- Support HTTP protocol and S3 Protocol
- Return copied object in the response
Fixes #611
> fix: allow copying objects to same destination and overwrite metadata

- src/storage/backend/file.ts
Earlier cache headers were only working with S3 backend added them to file backend too.
On S3 backend respond with correctly if-none-match and if-modified-since headers added.
Added these changes to file backend too.
> fix: added cache headers to file backend

- src/internal/database/util.ts
- src/test/database/util.test.ts
When storage is connecting via PgBouncer, we connect with an IPv6 address to keep traffic internal and avoid potential issues with network restrictions.
When customers enforce SSL verifications and we connect via IP address as hostname, requests will fail with an "SSL required" error. To address this, we do not let the requests fail, if the hostname cannot be validated, but we still connect via SSL. When using a regular domain/hostname (not an IP), we retain the old behaviour and verify the hostname as we usually do
> fix: disable hostname verification if connecting over an IP literal

- package-lock.json
- package.json
- src/internal/database/util.ts
The simpler regexps used earlier supported one of numerous IPv6 literal formats. The updated implementation uses a more comprehensive library.
> fix: update IP address literals detection routines

- migrations/tenant/0028-object-bucket-name-sorting.sql
- migrations/tenant/0029-create-prefixes.sql
- migrations/tenant/0030-update-object-levels.sql
- migrations/tenant/0036-optimise-existing-functions.sql
- src/http/routes/admin/migrations.ts
- src/http/routes/admin/objects.ts
- src/http/routes/admin/tenants.ts
- src/internal/database/migrations/migrate.ts
- src/internal/database/migrations/types.ts
- src/internal/queue/event.ts
- src/storage/events/run-migrations.ts
- src/test/tenant.test.ts
Bug fix
- Make sure only 1 jobs for migration is ever run
- Batch migration is now using an algorithm to increase / decrease delays and batch size depending on performance
- Starting batch size 10k
- Have batch size increase by 5k every iteration
- Measure execution time of each batch if it is over 3s reduce back to 10k
- If 10k is still slow decrease batch size -1k for each iteration until 5k
- Start with 1s delay
- Increase the delay to 1s for every iteration
- When reaches 30s reset back to 1s
> fix: improve migrations of prefixes

- migrations/multitenant/0016-tenants-jwks.sql
Bug fix
Currently we drop the `jwks` column in favour of using a new table
Do not drop the `jwks` just yet
This column is safe to be dropped; however, for a smooth deployment where the old version and new version of the containers are running, the creation of the tenant might fail if the new container is starting up and a tenant is created in the old container.
We will drop this column in a different PR
> fix: do not drop jwks column just yet

- .github/workflows/ci.yml
- .github/workflows/cli.yaml
- .github/workflows/docs.yml
- .github/workflows/mirror.yml
- .github/workflows/release.yml
Nothing vulnerable, just tightening up permissions
> ci: explicit permissions in actions

- src/scripts/migrate-call.ts
Bug fix
Allows CLI to freeze migrations at a specific version.
> fix: optionally freeze migrations when running migrate-call script

- src/internal/streams/ndjson.ts
- src/scripts/orphan-client.ts
- src/test/ndjson.test.ts
Bug fix
Client-side tool to interact with the object scanner to list and/or detect orphan objects.
This tool has 2 commands: `list` and `delete`
In both operations, detected orphans' references are saved to disk.
Is recommended to run the list command before delete
> fix: orphan object client detector

- src/http/routes/admin/tenants.ts
Bug fix 
PoolMode is not being update during Put requests on the tenant api
Update pool mode on PUT
> fix: update poolMode on put

- .github/workflows/ci.yml
- Dockerfile
- src/storage/protocols/s3/s3-handler.ts
- src/test/bucket.test.ts
- src/test/tenant.test.ts
Bug fix
S3 multipart uploads cannot complete in browser because they are unable to access the etag header since it is not included in the `Access-Control-Expose-Headers` of the response headers
Include etag in the `Access-Control-Expose-Headers` for only the S3 multipart upload requests. This allows using S3 multipart upload in browser.
- Fix for this issue: https://github.com/supabase/supabase-js/issues/1362
- capitalize "AS" in docker file to stop warning when building docker images
> fix: expose etag headers required for s3 multipart uploads in browser

- src/http/routes/admin/tenants.ts
- src/internal/database/tenant.ts
- src/test/tenant.test.ts
- src/test/x-forwarded-host.test.ts
Feature
- Expose capabilities of the server on a per tenant based
Adds the `capabilities` object to the admin tenant endpoint:
```json
{
"capabilities": {
"list_V2": false
}
}
```
> feat: capabilities

- src/internal/queue/queue.ts
Bug fix
Currently when creating queues concurrently the pgboss library encounter a deadlock.
Serially create and register workers
> fix: sequentially register tasks

- package-lock.json
- package.json
- src/config.ts
- src/internal/monitoring/logflare.ts
- src/internal/monitoring/logger.ts
Chore
Update pino and pino-logflare to newest version
Storage uses old pino-logflare which logs from the main event loop
Use latest version of pino-logflare to take advantage of latest performance enhancements including logging form a worker thread.
> chore: upgrade pino and pino-logflare to latest versions

- src/http/plugins/db.ts
- src/internal/database/tenant.ts
Bug fix
Not supporting temporary JWKS when jwt secret is revoked
Allows temporarily revoke JWT secret and allows authenticating with JWKS
> fix: new temporary api key support

- src/http/routes/bucket/getAllBuckets.ts
- src/storage/database/adapter.ts
- src/storage/database/knex.ts
- src/storage/storage.ts
- src/test/bucket.test.ts
Feature to add pagination to the GET buckets endpoint by introducing optional query parameters `limit`, `offset`, `sortColumn` and `sortOrder`
Currently, we do not allow pagination for GET buckets endpoint.
Now we allow optional query parameters to be passed in to allow pagination.
> feat: add pagination to getAllBuckets

- src/http/routes/s3/commands/upload-part.ts
Bug fix
S3 multi-part upload only allows 5000 parts
S3 multi-part upload allows 10,000 parts
> fix: allow 10,000 parts for s3 uploads

- docker-compose.yml
- src/config.ts
- src/http/routes/s3/commands/delete-object.ts
- src/storage/protocols/iceberg/knex.ts
Chore
Do not select redundant column
> fix: do not select redundant column

- src/internal/database/migrations/migrate.ts
- src/internal/database/tenant.ts
Bug fix
The `tenantHasMigrations()` function only checks migrations when running in multi-tenant mode 
Ensure we check for migrations when running in single-tenant / local mode too
> fix: check local migrations in tenantHasLocalMigrations()

- src/storage/backend/file.ts
Bug fix
Uploads fail when using file adapter if `content-type` or `cache-control` is not specified.
Use default values if `content-type` or `cache-control` is undefined to avoid error
Fixes: #719
> fix: gracefully handle missing metadata in file adapter

- src/storage/protocols/s3/signature-v4.ts
Bug fix
S3 calls that include an `accept-encoding` header fail to be verified because Cloudflare modifies this header. This impacts those using the Go SDK V2 (and potentially others)
Replace the (cloudflare modified) `accept-encoding` header with the value of `x-original-accept-encoding` so the request can be verified successfully.
- Fixes #646
- Fixes #577
- Depends on corresponding api gateway update to provide this new header value
> fix: use original accept encoding header to resolve s3 request signing issue

- src/storage/renderer/renderer.ts
- src/test/object.test.ts
Bug fix. 
When a filename is specified, the `content-disposition` header is added. Currently the header will have  content like this: 
```
attachment; filename=file.txt; filename*=UTF-8''file.txt;
```
RFC6266 specifies the valid formats for this header, and a trailing semi-colon is not allowed per the grammar at  https://datatracker.ietf.org/doc/html/rfc6266#page-4
I was prompted to raise this PR when I ran into the same issue discussed here: https://github.com/jshttp/content-disposition/issues/11
The PR removes the trailing semi-colon and updates the test for it. 
```
attachment; filename=file.txt; filename*=UTF-8''file.txt
```
> fix: Ensure Content-Disposition Header conforms to RFC6266

- .docker/docker-compose-infra.yml
- src/test/common.ts
- src/test/render-routes.test.ts
Bug fix
Imgproxy uses absolute path for lookup but can't find it
Make sure the volume is bound to the exact absolute path
> fix: imgproxy volume binding

- .docker/docker-compose-infra.yml
- migrations/tenant/0039-add-search-v2-sort-support.sql
- migrations/tenant/0040-fix-prefix-race-conditions-optimized.sql
- src/internal/database/migrations/types.ts
- src/test/prefixes.test.ts
This PR replaces our prefix GC logic with a **transaction-safe, concurrency-robust** design based on PostgreSQL **statement-level triggers** and **transition tables**. It removes the race condition that previously left dangling prefixes during concurrent deletes/moves—without introducing any external GC tables or background jobs.
---
**Current issue:** under concurrent deletes/moves, row-level triggers can evaluate leaf-ness before sibling transactions commit, clear their own work, and fail to restage parents → **dangling prefixes**.
**Goals:**
* Deterministic cleanup under concurrency
* No global serialization; allow parallelism across independent subtrees
* Keep the migration small & maintainable (no queue table / workers)
---
* **Statement-level triggers** with `REFERENCING OLD/NEW …
> fix: cleaning up of prefixes under heavy concurrency
